// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

type Certificate struct {
	Hostname    string
	Certificate string
	PrivateKey  string
}

type StatusPage struct {
	ID          int32
	Hostname    string
	PageDataUrl string
}
