// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package postgres

import (
	"context"
)

const getStatusPage = `-- name: GetStatusPage :one
SELECT page_data_url FROM status_pages WHERE hostname = $1 LIMIT 1
`

func (q *Queries) GetStatusPage(ctx context.Context, hostname string) (string, error) {
	row := q.db.QueryRow(ctx, getStatusPage, hostname)
	var page_data_url string
	err := row.Scan(&page_data_url)
	return page_data_url, err
}

const registerStatusPage = `-- name: RegisterStatusPage :one
INSERT INTO status_pages (
    hostname,
    page_data_url
) VALUES ($1, $2) RETURNING id
`

type RegisterStatusPageParams struct {
	Hostname    string
	PageDataUrl string
}

func (q *Queries) RegisterStatusPage(ctx context.Context, arg RegisterStatusPageParams) (int32, error) {
	row := q.db.QueryRow(ctx, registerStatusPage, arg.Hostname, arg.PageDataUrl)
	var id int32
	err := row.Scan(&id)
	return id, err
}
